# Generated by Django 5.0.1 on 2024-01-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=20)),
                ('image_url', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('category', models.CharField(max_length=50)),
                ('is_sale', models.BooleanField(default=False)),
                ('sale_price', models.CharField(blank=True, max_length=20, null=True)),
                ('new_product', models.BooleanField(default=False)),
            ],
        ),
    ]
