# Generated by Django 5.0.1 on 2024-01-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
