# Generated by Django 5.0.1 on 2024-01-20 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pive', '0002_product_description_product_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='product_images/'),
        ),
    ]
