// layout.tsx
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '../components/layout/footer' // Assuming the path is correct
import Navbar from '../components/layout/navbar/index' // Make sure the import path to Navbar.tsx is correct
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


type RootLayoutProps = {
  children: React.ReactNode; // Specify the type of children
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <>
    <body className={inter.className}>
      <Navbar />
        <main>{children}</main>
      <Footer />
    </body>
  </> 
  );
}